# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dins.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class dialyInspection(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1097, 997)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(220, 220, 220);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(20, -1, -1, -1)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.check5_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check5_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check5_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check5_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check5_3.setText("")
        self.check5_3.setChecked(False)
        self.check5_3.setAutoRepeat(False)
        self.check5_3.setAutoExclusive(False)
        self.check5_3.setTristate(False)
        self.check5_3.setObjectName("check5_3")
        self.gridLayout.addWidget(self.check5_3, 5, 4, 1, 1)
        self.check4_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check4_2.setText("")
        self.check4_2.setAutoExclusive(False)
        self.check4_2.setObjectName("check4_2")
        self.gridLayout.addWidget(self.check4_2, 4, 3, 1, 1)
        self.check13_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check13_2.setText("")
        self.check13_2.setAutoExclusive(False)
        self.check13_2.setObjectName("check13_2")
        self.gridLayout.addWidget(self.check13_2, 13, 3, 1, 1)
        self.check3_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check3_2.setText("")
        self.check3_2.setAutoExclusive(False)
        self.check3_2.setObjectName("check3_2")
        self.gridLayout.addWidget(self.check3_2, 3, 3, 1, 1)
        self.check2_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check2_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check2_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check2_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check2_3.setText("")
        self.check2_3.setChecked(False)
        self.check2_3.setAutoRepeat(False)
        self.check2_3.setAutoExclusive(False)
        self.check2_3.setTristate(False)
        self.check2_3.setObjectName("check2_3")
        self.gridLayout.addWidget(self.check2_3, 2, 4, 1, 1)
        self.check1_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1_2.setText("")
        self.check1_2.setAutoExclusive(False)
        self.check1_2.setObjectName("check1_2")
        self.gridLayout.addWidget(self.check1_2, 1, 3, 1, 1)
        self.check2_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check2_2.setText("")
        self.check2_2.setAutoExclusive(False)
        self.check2_2.setObjectName("check2_2")
        self.gridLayout.addWidget(self.check2_2, 2, 3, 1, 1)
        self.check8_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check8_2.setText("")
        self.check8_2.setAutoExclusive(False)
        self.check8_2.setObjectName("check8_2")
        self.gridLayout.addWidget(self.check8_2, 8, 3, 1, 1)
        self.check3_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check3_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check3_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check3_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check3_3.setText("")
        self.check3_3.setChecked(False)
        self.check3_3.setAutoRepeat(False)
        self.check3_3.setAutoExclusive(False)
        self.check3_3.setTristate(False)
        self.check3_3.setObjectName("check3_3")
        self.gridLayout.addWidget(self.check3_3, 3, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 1, 1, 1)
        self.check19_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check19_2.setText("")
        self.check19_2.setAutoExclusive(False)
        self.check19_2.setObjectName("check19_2")
        self.gridLayout.addWidget(self.check19_2, 20, 3, 1, 1)
        self.check12_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check12_2.setText("")
        self.check12_2.setAutoExclusive(False)
        self.check12_2.setObjectName("check12_2")
        self.gridLayout.addWidget(self.check12_2, 12, 3, 1, 1)
        self.check16_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check16_2.setText("")
        self.check16_2.setAutoExclusive(False)
        self.check16_2.setObjectName("check16_2")
        self.gridLayout.addWidget(self.check16_2, 17, 3, 1, 1)
        self.check4_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check4_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check4_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check4_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check4_3.setText("")
        self.check4_3.setChecked(False)
        self.check4_3.setAutoRepeat(False)
        self.check4_3.setAutoExclusive(False)
        self.check4_3.setTristate(False)
        self.check4_3.setObjectName("check4_3")
        self.gridLayout.addWidget(self.check4_3, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.check4_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check4_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check4_1.setText("")
        self.check4_1.setAutoExclusive(False)
        self.check4_1.setObjectName("check4_1")
        self.gridLayout.addWidget(self.check4_1, 4, 1, 1, 1)
        self.check13_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check13_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check13_1.setText("")
        self.check13_1.setAutoExclusive(False)
        self.check13_1.setObjectName("check13_1")
        self.gridLayout.addWidget(self.check13_1, 13, 1, 1, 1)
        self.check1_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check1_1.setText("")
        self.check1_1.setAutoExclusive(False)
        self.check1_1.setObjectName("check1_1")
        self.gridLayout.addWidget(self.check1_1, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 15, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        self.check6_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check6_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check6_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check6_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check6_3.setText("")
        self.check6_3.setChecked(False)
        self.check6_3.setAutoRepeat(False)
        self.check6_3.setAutoExclusive(False)
        self.check6_3.setTristate(False)
        self.check6_3.setObjectName("check6_3")
        self.gridLayout.addWidget(self.check6_3, 6, 4, 1, 1)
        self.check16_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check16_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check16_1.setText("")
        self.check16_1.setAutoExclusive(False)
        self.check16_1.setObjectName("check16_1")
        self.gridLayout.addWidget(self.check16_1, 17, 1, 1, 1)
        self.check16_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check16_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check16_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check16_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check16_3.setText("")
        self.check16_3.setChecked(False)
        self.check16_3.setAutoRepeat(False)
        self.check16_3.setAutoExclusive(False)
        self.check16_3.setTristate(False)
        self.check16_3.setObjectName("check16_3")
        self.gridLayout.addWidget(self.check16_3, 17, 4, 1, 1)
        self.check18_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check18_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check18_1.setText("")
        self.check18_1.setAutoExclusive(False)
        self.check18_1.setObjectName("check18_1")
        self.gridLayout.addWidget(self.check18_1, 19, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 1)
        self.check17_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check17_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check17_1.setText("")
        self.check17_1.setAutoExclusive(False)
        self.check17_1.setObjectName("check17_1")
        self.gridLayout.addWidget(self.check17_1, 18, 1, 1, 1)
        self.check14_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check14_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check14_1.setText("")
        self.check14_1.setAutoExclusive(False)
        self.check14_1.setObjectName("check14_1")
        self.gridLayout.addWidget(self.check14_1, 15, 1, 1, 1)
        self.check3_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check3_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check3_1.setText("")
        self.check3_1.setAutoExclusive(False)
        self.check3_1.setObjectName("check3_1")
        self.gridLayout.addWidget(self.check3_1, 3, 1, 1, 1)
        self.check2_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check2_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check2_1.setText("")
        self.check2_1.setAutoExclusive(False)
        self.check2_1.setObjectName("check2_1")
        self.gridLayout.addWidget(self.check2_1, 2, 1, 1, 1)
        self.check7_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check7_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check7_1.setText("")
        self.check7_1.setAutoExclusive(False)
        self.check7_1.setObjectName("check7_1")
        self.gridLayout.addWidget(self.check7_1, 7, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.check10_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check10_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check10_1.setText("")
        self.check10_1.setAutoExclusive(False)
        self.check10_1.setObjectName("check10_1")
        self.gridLayout.addWidget(self.check10_1, 10, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 17, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 16, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 20, 0, 1, 1)
        self.check14_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check14_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check14_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check14_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check14_3.setText("")
        self.check14_3.setChecked(False)
        self.check14_3.setAutoRepeat(False)
        self.check14_3.setAutoExclusive(False)
        self.check14_3.setTristate(False)
        self.check14_3.setObjectName("check14_3")
        self.gridLayout.addWidget(self.check14_3, 15, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 19, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 1)
        self.check11_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check11_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check11_1.setText("")
        self.check11_1.setAutoExclusive(False)
        self.check11_1.setObjectName("check11_1")
        self.gridLayout.addWidget(self.check11_1, 11, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 18, 0, 1, 1)
        self.check19_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check19_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check19_1.setText("")
        self.check19_1.setAutoExclusive(False)
        self.check19_1.setObjectName("check19_1")
        self.gridLayout.addWidget(self.check19_1, 20, 1, 1, 1)
        self.check13_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check13_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check13_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check13_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check13_3.setText("")
        self.check13_3.setChecked(False)
        self.check13_3.setAutoRepeat(False)
        self.check13_3.setAutoExclusive(False)
        self.check13_3.setTristate(False)
        self.check13_3.setObjectName("check13_3")
        self.gridLayout.addWidget(self.check13_3, 13, 4, 1, 1)
        self.check15_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check15_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check15_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check15_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check15_3.setText("")
        self.check15_3.setChecked(False)
        self.check15_3.setAutoRepeat(False)
        self.check15_3.setAutoExclusive(False)
        self.check15_3.setTristate(False)
        self.check15_3.setObjectName("check15_3")
        self.gridLayout.addWidget(self.check15_3, 16, 4, 1, 1)
        self.check10_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check10_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check10_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check10_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check10_3.setText("")
        self.check10_3.setChecked(False)
        self.check10_3.setAutoRepeat(False)
        self.check10_3.setAutoExclusive(False)
        self.check10_3.setTristate(False)
        self.check10_3.setObjectName("check10_3")
        self.gridLayout.addWidget(self.check10_3, 10, 4, 1, 1)
        self.check15_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check15_2.setText("")
        self.check15_2.setAutoExclusive(False)
        self.check15_2.setObjectName("check15_2")
        self.gridLayout.addWidget(self.check15_2, 16, 3, 1, 1)
        self.check12_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check12_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check12_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check12_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check12_3.setText("")
        self.check12_3.setChecked(False)
        self.check12_3.setAutoRepeat(False)
        self.check12_3.setAutoExclusive(False)
        self.check12_3.setTristate(False)
        self.check12_3.setObjectName("check12_3")
        self.gridLayout.addWidget(self.check12_3, 12, 4, 1, 1)
        self.check17_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check17_2.setText("")
        self.check17_2.setAutoExclusive(False)
        self.check17_2.setObjectName("check17_2")
        self.gridLayout.addWidget(self.check17_2, 18, 3, 1, 1)
        self.check7_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check7_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check7_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check7_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check7_3.setText("")
        self.check7_3.setChecked(False)
        self.check7_3.setAutoRepeat(False)
        self.check7_3.setAutoExclusive(False)
        self.check7_3.setTristate(False)
        self.check7_3.setObjectName("check7_3")
        self.gridLayout.addWidget(self.check7_3, 7, 4, 1, 1)
        self.check6_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check6_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check6_1.setText("")
        self.check6_1.setAutoExclusive(False)
        self.check6_1.setObjectName("check6_1")
        self.gridLayout.addWidget(self.check6_1, 6, 1, 1, 1)
        self.check18_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check18_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check18_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check18_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check18_3.setText("")
        self.check18_3.setChecked(False)
        self.check18_3.setAutoRepeat(False)
        self.check18_3.setAutoExclusive(False)
        self.check18_3.setTristate(False)
        self.check18_3.setObjectName("check18_3")
        self.gridLayout.addWidget(self.check18_3, 19, 4, 1, 1)
        self.check8_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check8_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check8_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check8_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check8_3.setText("")
        self.check8_3.setChecked(False)
        self.check8_3.setAutoRepeat(False)
        self.check8_3.setAutoExclusive(False)
        self.check8_3.setTristate(False)
        self.check8_3.setObjectName("check8_3")
        self.gridLayout.addWidget(self.check8_3, 8, 4, 1, 1)
        self.check9_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check9_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check9_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check9_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check9_3.setText("")
        self.check9_3.setChecked(False)
        self.check9_3.setAutoRepeat(False)
        self.check9_3.setAutoExclusive(False)
        self.check9_3.setTristate(False)
        self.check9_3.setObjectName("check9_3")
        self.gridLayout.addWidget(self.check9_3, 9, 4, 1, 1)
        self.check17_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check17_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check17_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check17_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check17_3.setText("")
        self.check17_3.setChecked(False)
        self.check17_3.setAutoRepeat(False)
        self.check17_3.setAutoExclusive(False)
        self.check17_3.setTristate(False)
        self.check17_3.setObjectName("check17_3")
        self.gridLayout.addWidget(self.check17_3, 18, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 7, 0, 1, 1)
        self.check9_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check9_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check9_1.setText("")
        self.check9_1.setAutoExclusive(False)
        self.check9_1.setObjectName("check9_1")
        self.gridLayout.addWidget(self.check9_1, 9, 1, 1, 1)
        self.check5_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check5_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check5_1.setText("")
        self.check5_1.setAutoExclusive(False)
        self.check5_1.setObjectName("check5_1")
        self.gridLayout.addWidget(self.check5_1, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_20.setFont(font)
        self.label_20.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 0, 1, 1)
        self.check9_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check9_2.setText("")
        self.check9_2.setAutoExclusive(False)
        self.check9_2.setObjectName("check9_2")
        self.gridLayout.addWidget(self.check9_2, 9, 3, 1, 1)
        self.check14_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check14_2.setText("")
        self.check14_2.setAutoExclusive(False)
        self.check14_2.setObjectName("check14_2")
        self.gridLayout.addWidget(self.check14_2, 15, 3, 1, 1)
        self.check11_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check11_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check11_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check11_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check11_3.setText("")
        self.check11_3.setChecked(False)
        self.check11_3.setAutoRepeat(False)
        self.check11_3.setAutoExclusive(False)
        self.check11_3.setTristate(False)
        self.check11_3.setObjectName("check11_3")
        self.gridLayout.addWidget(self.check11_3, 11, 4, 1, 1)
        self.check15_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check15_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check15_1.setText("")
        self.check15_1.setAutoExclusive(False)
        self.check15_1.setObjectName("check15_1")
        self.gridLayout.addWidget(self.check15_1, 16, 1, 1, 1)
        self.check8_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check8_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check8_1.setText("")
        self.check8_1.setAutoExclusive(False)
        self.check8_1.setObjectName("check8_1")
        self.gridLayout.addWidget(self.check8_1, 8, 1, 1, 1)
        self.check12_1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check12_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check12_1.setText("")
        self.check12_1.setAutoExclusive(False)
        self.check12_1.setObjectName("check12_1")
        self.gridLayout.addWidget(self.check12_1, 12, 1, 1, 1)
        self.check6_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check6_2.setText("")
        self.check6_2.setAutoExclusive(False)
        self.check6_2.setObjectName("check6_2")
        self.gridLayout.addWidget(self.check6_2, 6, 3, 1, 1)
        self.check5_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check5_2.setText("")
        self.check5_2.setAutoExclusive(False)
        self.check5_2.setObjectName("check5_2")
        self.gridLayout.addWidget(self.check5_2, 5, 3, 1, 1)
        self.check7_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check7_2.setText("")
        self.check7_2.setAutoExclusive(False)
        self.check7_2.setObjectName("check7_2")
        self.gridLayout.addWidget(self.check7_2, 7, 3, 1, 1)
        self.check1_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check1_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check1_3.setText("")
        self.check1_3.setChecked(False)
        self.check1_3.setAutoRepeat(False)
        self.check1_3.setAutoExclusive(False)
        self.check1_3.setTristate(False)
        self.check1_3.setObjectName("check1_3")
        self.gridLayout.addWidget(self.check1_3, 1, 4, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 0, 4, 1, 1)
        self.check11_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check11_2.setText("")
        self.check11_2.setAutoExclusive(False)
        self.check11_2.setObjectName("check11_2")
        self.gridLayout.addWidget(self.check11_2, 11, 3, 1, 1)
        self.check19_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check19_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.check19_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.check19_3.setInputMethodHints(QtCore.Qt.ImhNone)
        self.check19_3.setText("")
        self.check19_3.setChecked(False)
        self.check19_3.setAutoRepeat(False)
        self.check19_3.setAutoExclusive(False)
        self.check19_3.setTristate(False)
        self.check19_3.setObjectName("check19_3")
        self.gridLayout.addWidget(self.check19_3, 20, 4, 1, 1)
        self.check18_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check18_2.setText("")
        self.check18_2.setAutoExclusive(False)
        self.check18_2.setObjectName("check18_2")
        self.gridLayout.addWidget(self.check18_2, 19, 3, 1, 1)
        self.check10_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check10_2.setText("")
        self.check10_2.setAutoExclusive(False)
        self.check10_2.setObjectName("check10_2")
        self.gridLayout.addWidget(self.check10_2, 10, 3, 1, 1)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setMaximumSize(QtCore.QSize(90, 16777215))
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 21, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialy Inspection"))
        self.label_21.setText(_translate("MainWindow", "EXISTING"))
        self.label.setText(_translate("MainWindow", "Presence of all accessories required for proper operation"))
        self.label_17.setText(_translate("MainWindow", "Calibration stickers"))
        self.label_12.setText(_translate("MainWindow", "Equipment cards"))
        self.label_4.setText(_translate("MainWindow", "Electrical connectors(jacks,receptacles or plugs))"))
        self.label_9.setText(_translate("MainWindow", "Audible Signals"))
        self.label_22.setText(_translate("MainWindow", "INCOMPLETE"))
        self.label_11.setText(_translate("MainWindow", "Availability and validity of consumables"))
        self.label_3.setText(_translate("MainWindow", "Proper operation of the equipment as specified in the manufacturer\'s service literature."))
        self.label_5.setText(_translate("MainWindow", "Alarms"))
        self.label_8.setText(_translate("MainWindow", "Indicators/Displays"))
        self.label_10.setText(_translate("MainWindow", "Battery/Charger"))
        self.label_6.setText(_translate("MainWindow", "circuit Breakers/Fuse"))
        self.label_16.setText(_translate("MainWindow", "Freeing device intemally and extemally from rust and corrosion, liquids and dust"))
        self.label_15.setText(_translate("MainWindow", "Suitable environment for equipment"))
        self.label_19.setText(_translate("MainWindow", "Checking the Nuts, bolts, screws and other hardware"))
        self.label_18.setText(_translate("MainWindow", "Checking the component holders, clips and receptacles"))
        self.label_13.setText(_translate("MainWindow", "Connecting the device to the grounding system"))
        self.label_14.setText(_translate("MainWindow", "Doors, knobs and the other of the moving parts are working well"))
        self.label_2.setText(_translate("MainWindow", "Standard operating procedure (SOP)"))
        self.label_7.setText(_translate("MainWindow", "Controls/Switches"))
        self.label_20.setText(_translate("MainWindow", "Item"))
        self.label_23.setText(_translate("MainWindow", "NOT EXISTING"))
        self.save.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = dialyInspection()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
