# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inst.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class installation(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1253, 994)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.tabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabs.sizePolicy().hasHeightForWidth())
        self.tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tabs.setFont(font)
        self.tabs.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.tabs.setObjectName("tabs")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setEnabled(True)
        self.tab1.setObjectName("tab1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.tab1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, -1, -1, 500)
        self.gridLayout_5.setHorizontalSpacing(30)
        self.gridLayout_5.setVerticalSpacing(50)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_25 = QtWidgets.QLabel(self.tab1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 1, 0, 1, 1)
        self.model = QtWidgets.QLineEdit(self.tab1)
        self.model.setText("")
        self.model.setObjectName("model")
        self.gridLayout_5.addWidget(self.model, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 4, 0, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.tab1)
        self.label_61.setObjectName("label_61")
        self.gridLayout_5.addWidget(self.label_61, 3, 0, 1, 1)
        self.brand = QtWidgets.QLineEdit(self.tab1)
        self.brand.setText("")
        self.brand.setObjectName("brand")
        self.gridLayout_5.addWidget(self.brand, 3, 1, 1, 1)
        self.manufacturer = QtWidgets.QLineEdit(self.tab1)
        self.manufacturer.setText("")
        self.manufacturer.setObjectName("manufacturer")
        self.gridLayout_5.addWidget(self.manufacturer, 4, 1, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.tab1)
        self.label_68.setObjectName("label_68")
        self.gridLayout_5.addWidget(self.label_68, 3, 2, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.tab1)
        self.label_66.setObjectName("label_66")
        self.gridLayout_5.addWidget(self.label_66, 1, 2, 1, 1)
        self.riskClassification = QtWidgets.QLineEdit(self.tab1)
        self.riskClassification.setText("")
        self.riskClassification.setObjectName("riskClassification")
        self.gridLayout_5.addWidget(self.riskClassification, 3, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.tab1)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 2, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.tab1)
        self.name.setText("")
        self.name.setObjectName("name")
        self.gridLayout_5.addWidget(self.name, 1, 1, 1, 1)
        self.tab0Next = QtWidgets.QPushButton(self.tab1)
        self.tab0Next.setObjectName("tab0Next")
        self.gridLayout_5.addWidget(self.tab0Next, 5, 3, 1, 1)
        self.serialNumber = QtWidgets.QLineEdit(self.tab1)
        self.serialNumber.setText("")
        self.serialNumber.setObjectName("serialNumber")
        self.gridLayout_5.addWidget(self.serialNumber, 2, 3, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.tab1)
        self.label_67.setObjectName("label_67")
        self.gridLayout_5.addWidget(self.label_67, 4, 2, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.tab1)
        self.label_65.setObjectName("label_65")
        self.gridLayout_5.addWidget(self.label_65, 2, 2, 1, 1)
        self.description = QtWidgets.QLineEdit(self.tab1)
        self.description.setText("")
        self.description.setObjectName("description")
        self.gridLayout_5.addWidget(self.description, 4, 3, 1, 1)
        self.department = QtWidgets.QComboBox(self.tab1)
        self.department.setMinimumSize(QtCore.QSize(0, 30))
        self.department.setCurrentText("")
        self.department.setIconSize(QtCore.QSize(20, 30))
        self.department.setDuplicatesEnabled(False)
        self.department.setObjectName("department")
        self.department.addItem("")
        self.department.addItem("")
        self.department.addItem("")
        self.gridLayout_5.addWidget(self.department, 1, 3, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_5, 2, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab1)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 0, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.tab1)
        self.line_9.setLineWidth(2)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_13.addWidget(self.line_9, 1, 0, 1, 1)
        self.tabs.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setEnabled(False)
        self.tab2.setAutoFillBackground(False)
        self.tab2.setObjectName("tab2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(-1, 20, 20, 20)
        self.gridLayout_4.setHorizontalSpacing(50)
        self.gridLayout_4.setVerticalSpacing(20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_20 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 2, 0, 1, 1)
        self.localPurchaseOrderNO = QtWidgets.QLineEdit(self.tab2)
        self.localPurchaseOrderNO.setObjectName("localPurchaseOrderNO")
        self.gridLayout_4.addWidget(self.localPurchaseOrderNO, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 1, 0, 1, 1)
        self.deliveryNO = QtWidgets.QLineEdit(self.tab2)
        self.deliveryNO.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.deliveryNO.setText("")
        self.deliveryNO.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.deliveryNO.setObjectName("deliveryNO")
        self.gridLayout_4.addWidget(self.deliveryNO, 1, 3, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 2, 2, 1, 1)
        self.purchasePrice = QtWidgets.QLineEdit(self.tab2)
        self.purchasePrice.setObjectName("purchasePrice")
        self.gridLayout_4.addWidget(self.purchasePrice, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 1, 2, 1, 1)
        self.purchaseDate = QtWidgets.QDateEdit(self.tab2)
        self.purchaseDate.setObjectName("purchaseDate")
        self.gridLayout_4.addWidget(self.purchaseDate, 1, 1, 1, 1)
        self.warrantyStartDate = QtWidgets.QDateEdit(self.tab2)
        self.warrantyStartDate.setObjectName("warrantyStartDate")
        self.gridLayout_4.addWidget(self.warrantyStartDate, 2, 1, 1, 1)
        self.warrantyEndDate = QtWidgets.QDateEdit(self.tab2)
        self.warrantyEndDate.setObjectName("warrantyEndDate")
        self.gridLayout_4.addWidget(self.warrantyEndDate, 2, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab1Back = QtWidgets.QPushButton(self.tab2)
        self.tab1Back.setObjectName("tab1Back")
        self.horizontalLayout.addWidget(self.tab1Back)
        self.tab1Next = QtWidgets.QPushButton(self.tab2)
        self.tab1Next.setObjectName("tab1Next")
        self.horizontalLayout.addWidget(self.tab1Next)
        self.gridLayout_9.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_9.addWidget(self.line_3, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 20, 20, 20)
        self.gridLayout_3.setHorizontalSpacing(50)
        self.gridLayout_3.setVerticalSpacing(20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.authorisedContactPerson = QtWidgets.QLineEdit(self.tab2)
        self.authorisedContactPerson.setObjectName("authorisedContactPerson")
        self.gridLayout_3.addWidget(self.authorisedContactPerson, 0, 3, 1, 1)
        self.authorised = QtWidgets.QLineEdit(self.tab2)
        self.authorised.setObjectName("authorised")
        self.gridLayout_3.addWidget(self.authorised, 0, 1, 1, 1)
        self.authorisedContactNO = QtWidgets.QLineEdit(self.tab2)
        self.authorisedContactNO.setObjectName("authorisedContactNO")
        self.gridLayout_3.addWidget(self.authorisedContactNO, 1, 3, 1, 1)
        self.Authorised = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Authorised.setFont(font)
        self.Authorised.setObjectName("Authorised")
        self.gridLayout_3.addWidget(self.Authorised, 0, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 2, 1, 1)
        self.authorisedAddress = QtWidgets.QLineEdit(self.tab2)
        self.authorisedAddress.setObjectName("authorisedAddress")
        self.gridLayout_3.addWidget(self.authorisedAddress, 1, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 20, -1, 20)
        self.gridLayout.setHorizontalSpacing(50)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.supplierAddress = QtWidgets.QLineEdit(self.tab2)
        self.supplierAddress.setObjectName("supplierAddress")
        self.gridLayout.addWidget(self.supplierAddress, 1, 1, 1, 1)
        self.supplierContactPerson = QtWidgets.QLineEdit(self.tab2)
        self.supplierContactPerson.setObjectName("supplierContactPerson")
        self.gridLayout.addWidget(self.supplierContactPerson, 0, 3, 1, 1)
        self.supplier = QtWidgets.QLineEdit(self.tab2)
        self.supplier.setObjectName("supplier")
        self.gridLayout.addWidget(self.supplier, 0, 1, 1, 1)
        self.supplierContactNO = QtWidgets.QLineEdit(self.tab2)
        self.supplierContactNO.setObjectName("supplierContactNO")
        self.gridLayout.addWidget(self.supplierContactNO, 1, 3, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem, 7, 0, 1, 1)
        self.tabs.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setEnabled(False)
        self.tab3.setObjectName("tab3")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.tab3)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_23 = QtWidgets.QLabel(self.tab3)
        self.label_23.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_23.setScaledContents(False)
        self.label_23.setWordWrap(False)
        self.label_23.setIndent(0)
        self.label_23.setOpenExternalLinks(False)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.label_92 = QtWidgets.QLabel(self.tab3)
        self.label_92.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_92.setIndent(0)
        self.label_92.setObjectName("label_92")
        self.horizontalLayout_8.addWidget(self.label_92)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line_7 = QtWidgets.QFrame(self.tab3)
        self.line_7.setLineWidth(2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_2.setSpacing(30)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.batchSize = QtWidgets.QLineEdit(self.tab3)
        self.batchSize.setObjectName("batchSize")
        self.horizontalLayout_2.addWidget(self.batchSize)
        self.label_7 = QtWidgets.QLabel(self.tab3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.sampleSize = QtWidgets.QLineEdit(self.tab3)
        self.sampleSize.setObjectName("sampleSize")
        self.horizontalLayout_2.addWidget(self.sampleSize)
        self.label_8 = QtWidgets.QLabel(self.tab3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.defectsCount = QtWidgets.QLineEdit(self.tab3)
        self.defectsCount.setObjectName("defectsCount")
        self.horizontalLayout_2.addWidget(self.defectsCount)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.gridLayout_2.setSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_62 = QtWidgets.QLabel(self.tab3)
        self.label_62.setObjectName("label_62")
        self.gridLayout_2.addWidget(self.label_62, 7, 0, 1, 1)
        self.check7_2 = QtWidgets.QCheckBox(self.tab3)
        self.check7_2.setText("")
        self.check7_2.setObjectName("check7_2")
        self.gridLayout_2.addWidget(self.check7_2, 7, 2, 1, 1)
        self.check7_1 = QtWidgets.QCheckBox(self.tab3)
        self.check7_1.setText("")
        self.check7_1.setObjectName("check7_1")
        self.gridLayout_2.addWidget(self.check7_1, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 0, 1, 1)
        self.check3_3 = QtWidgets.QCheckBox(self.tab3)
        self.check3_3.setText("")
        self.check3_3.setObjectName("check3_3")
        self.gridLayout_2.addWidget(self.check3_3, 3, 3, 1, 1)
        self.check1_3 = QtWidgets.QCheckBox(self.tab3)
        self.check1_3.setText("")
        self.check1_3.setObjectName("check1_3")
        self.gridLayout_2.addWidget(self.check1_3, 1, 3, 1, 1)
        self.check4_1 = QtWidgets.QCheckBox(self.tab3)
        self.check4_1.setText("")
        self.check4_1.setObjectName("check4_1")
        self.gridLayout_2.addWidget(self.check4_1, 4, 1, 1, 1)
        self.check1_2 = QtWidgets.QCheckBox(self.tab3)
        self.check1_2.setText("")
        self.check1_2.setObjectName("check1_2")
        self.gridLayout_2.addWidget(self.check1_2, 1, 2, 1, 1)
        self.check2_1 = QtWidgets.QCheckBox(self.tab3)
        self.check2_1.setText("")
        self.check2_1.setObjectName("check2_1")
        self.gridLayout_2.addWidget(self.check2_1, 2, 1, 1, 1)
        self.check1_1 = QtWidgets.QCheckBox(self.tab3)
        self.check1_1.setText("")
        self.check1_1.setObjectName("check1_1")
        self.gridLayout_2.addWidget(self.check1_1, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
        self.check5_1 = QtWidgets.QCheckBox(self.tab3)
        self.check5_1.setText("")
        self.check5_1.setObjectName("check5_1")
        self.gridLayout_2.addWidget(self.check5_1, 5, 1, 1, 1)
        self.check5_2 = QtWidgets.QCheckBox(self.tab3)
        self.check5_2.setText("")
        self.check5_2.setObjectName("check5_2")
        self.gridLayout_2.addWidget(self.check5_2, 5, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 0, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 0, 1, 1, 1)
        self.check5_3 = QtWidgets.QCheckBox(self.tab3)
        self.check5_3.setText("")
        self.check5_3.setObjectName("check5_3")
        self.gridLayout_2.addWidget(self.check5_3, 5, 3, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.tab3)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 0, 2, 1, 1)
        self.check4_3 = QtWidgets.QCheckBox(self.tab3)
        self.check4_3.setText("")
        self.check4_3.setObjectName("check4_3")
        self.gridLayout_2.addWidget(self.check4_3, 4, 3, 1, 1)
        self.check2_3 = QtWidgets.QCheckBox(self.tab3)
        self.check2_3.setText("")
        self.check2_3.setObjectName("check2_3")
        self.gridLayout_2.addWidget(self.check2_3, 2, 3, 1, 1)
        self.check2_2 = QtWidgets.QCheckBox(self.tab3)
        self.check2_2.setText("")
        self.check2_2.setObjectName("check2_2")
        self.gridLayout_2.addWidget(self.check2_2, 2, 2, 1, 1)
        self.check3_1 = QtWidgets.QCheckBox(self.tab3)
        self.check3_1.setText("")
        self.check3_1.setObjectName("check3_1")
        self.gridLayout_2.addWidget(self.check3_1, 3, 1, 1, 1)
        self.check3_2 = QtWidgets.QCheckBox(self.tab3)
        self.check3_2.setText("")
        self.check3_2.setObjectName("check3_2")
        self.gridLayout_2.addWidget(self.check3_2, 3, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        self.check4_2 = QtWidgets.QCheckBox(self.tab3)
        self.check4_2.setText("")
        self.check4_2.setObjectName("check4_2")
        self.gridLayout_2.addWidget(self.check4_2, 4, 2, 1, 1)
        self.check7_3 = QtWidgets.QCheckBox(self.tab3)
        self.check7_3.setText("")
        self.check7_3.setObjectName("check7_3")
        self.gridLayout_2.addWidget(self.check7_3, 7, 3, 1, 1)
        self.check6_2 = QtWidgets.QCheckBox(self.tab3)
        self.check6_2.setText("")
        self.check6_2.setObjectName("check6_2")
        self.gridLayout_2.addWidget(self.check6_2, 6, 2, 1, 1)
        self.check6_3 = QtWidgets.QCheckBox(self.tab3)
        self.check6_3.setText("")
        self.check6_3.setObjectName("check6_3")
        self.gridLayout_2.addWidget(self.check6_3, 6, 3, 1, 1)
        self.check6_1 = QtWidgets.QCheckBox(self.tab3)
        self.check6_1.setText("")
        self.check6_1.setObjectName("check6_1")
        self.gridLayout_2.addWidget(self.check6_1, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_24.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_91 = QtWidgets.QLabel(self.tab3)
        self.label_91.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_91.setFont(font)
        self.label_91.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_91.setScaledContents(False)
        self.label_91.setWordWrap(False)
        self.label_91.setIndent(0)
        self.label_91.setOpenExternalLinks(False)
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_9.addWidget(self.label_91)
        self.label_93 = QtWidgets.QLabel(self.tab3)
        self.label_93.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_93.setIndent(0)
        self.label_93.setObjectName("label_93")
        self.horizontalLayout_9.addWidget(self.label_93)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.line_18 = QtWidgets.QFrame(self.tab3)
        self.line_18.setLineWidth(2)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.verticalLayout_4.addWidget(self.line_18)
        self.label_94 = QtWidgets.QLabel(self.tab3)
        self.label_94.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_94.setFont(font)
        self.label_94.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_94.setIndent(0)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_4.addWidget(self.label_94)
        self.problem = QtWidgets.QTextEdit(self.tab3)
        self.problem.setObjectName("problem")
        self.verticalLayout_4.addWidget(self.problem)
        self.label_95 = QtWidgets.QLabel(self.tab3)
        self.label_95.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_95.setFont(font)
        self.label_95.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_95.setIndent(0)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_4.addWidget(self.label_95)
        self.remarks = QtWidgets.QTextEdit(self.tab3)
        self.remarks.setObjectName("remarks")
        self.verticalLayout_4.addWidget(self.remarks)
        self.label_129 = QtWidgets.QLabel(self.tab3)
        self.label_129.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_129.setFont(font)
        self.label_129.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_129.setIndent(0)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_4.addWidget(self.label_129)
        self.suggestion = QtWidgets.QTextEdit(self.tab3)
        self.suggestion.setObjectName("suggestion")
        self.verticalLayout_4.addWidget(self.suggestion)
        self.gridLayout_24.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.tab2Back = QtWidgets.QPushButton(self.tab3)
        self.tab2Back.setObjectName("tab2Back")
        self.horizontalLayout_19.addWidget(self.tab2Back)
        self.tab2Next = QtWidgets.QPushButton(self.tab3)
        self.tab2Next.setObjectName("tab2Next")
        self.horizontalLayout_19.addWidget(self.tab2Next)
        self.gridLayout_24.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.tabs.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setEnabled(False)
        self.tab4.setObjectName("tab4")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.tab4)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_130 = QtWidgets.QLabel(self.tab4)
        self.label_130.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_130.setFont(font)
        self.label_130.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_130.setScaledContents(False)
        self.label_130.setWordWrap(False)
        self.label_130.setIndent(0)
        self.label_130.setOpenExternalLinks(False)
        self.label_130.setObjectName("label_130")
        self.horizontalLayout_14.addWidget(self.label_130)
        self.label_131 = QtWidgets.QLabel(self.tab4)
        self.label_131.setMinimumSize(QtCore.QSize(0, 50))
        self.label_131.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_131.setFont(font)
        self.label_131.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_131.setIndent(0)
        self.label_131.setObjectName("label_131")
        self.horizontalLayout_14.addWidget(self.label_131)
        self.gridLayout_26.addLayout(self.horizontalLayout_14, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(100)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.inspectionDone = QtWidgets.QCheckBox(self.tab4)
        self.inspectionDone.setObjectName("inspectionDone")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.inspectionDone)
        self.inspectionNOTDone = QtWidgets.QCheckBox(self.tab4)
        self.inspectionNOTDone.setObjectName("inspectionNOTDone")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.inspectionNOTDone)
        self.accepted = QtWidgets.QCheckBox(self.tab4)
        self.accepted.setObjectName("accepted")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.accepted)
        self.notAccepted = QtWidgets.QCheckBox(self.tab4)
        self.notAccepted.setObjectName("notAccepted")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.notAccepted)
        self.acceptedWithReservation = QtWidgets.QCheckBox(self.tab4)
        self.acceptedWithReservation.setObjectName("acceptedWithReservation")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.acceptedWithReservation)
        self.label_132 = QtWidgets.QLabel(self.tab4)
        self.label_132.setObjectName("label_132")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_132)
        self.remark = QtWidgets.QLineEdit(self.tab4)
        self.remark.setObjectName("remark")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.remark)
        self.gridLayout_26.addLayout(self.formLayout, 1, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_133 = QtWidgets.QLabel(self.tab4)
        self.label_133.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_133.setFont(font)
        self.label_133.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.label_133.setScaledContents(False)
        self.label_133.setWordWrap(False)
        self.label_133.setIndent(0)
        self.label_133.setOpenExternalLinks(False)
        self.label_133.setObjectName("label_133")
        self.horizontalLayout_15.addWidget(self.label_133)
        self.label_134 = QtWidgets.QLabel(self.tab4)
        self.label_134.setMinimumSize(QtCore.QSize(0, 50))
        self.label_134.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_134.setFont(font)
        self.label_134.setStyleSheet("background-color: rgb(157, 157, 157);\n"
"")
        self.label_134.setIndent(0)
        self.label_134.setObjectName("label_134")
        self.horizontalLayout_15.addWidget(self.label_134)
        self.gridLayout_26.addLayout(self.horizontalLayout_15, 2, 0, 1, 1)
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setContentsMargins(-1, -1, -1, 350)
        self.gridLayout_25.setHorizontalSpacing(50)
        self.gridLayout_25.setVerticalSpacing(20)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_139 = QtWidgets.QLabel(self.tab4)
        self.label_139.setObjectName("label_139")
        self.gridLayout_25.addWidget(self.label_139, 1, 3, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.tab4)
        self.label_140.setObjectName("label_140")
        self.gridLayout_25.addWidget(self.label_140, 2, 3, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.tab4)
        self.label_136.setObjectName("label_136")
        self.gridLayout_25.addWidget(self.label_136, 1, 0, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.tab4)
        self.label_137.setObjectName("label_137")
        self.gridLayout_25.addWidget(self.label_137, 2, 0, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.tab4)
        self.label_138.setObjectName("label_138")
        self.gridLayout_25.addWidget(self.label_138, 3, 0, 1, 1)
        self.supplierDesignation = QtWidgets.QLineEdit(self.tab4)
        self.supplierDesignation.setObjectName("supplierDesignation")
        self.gridLayout_25.addWidget(self.supplierDesignation, 2, 1, 1, 1)
        self.supplierName = QtWidgets.QLineEdit(self.tab4)
        self.supplierName.setObjectName("supplierName")
        self.gridLayout_25.addWidget(self.supplierName, 1, 1, 1, 1)
        self.supplierDate = QtWidgets.QDateEdit(self.tab4)
        self.supplierDate.setObjectName("supplierDate")
        self.gridLayout_25.addWidget(self.supplierDate, 3, 1, 1, 1)
        self.hospitalRepresentativeDate = QtWidgets.QDateEdit(self.tab4)
        self.hospitalRepresentativeDate.setObjectName("hospitalRepresentativeDate")
        self.gridLayout_25.addWidget(self.hospitalRepresentativeDate, 3, 4, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.tab4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_135.setFont(font)
        self.label_135.setObjectName("label_135")
        self.gridLayout_25.addWidget(self.label_135, 0, 0, 1, 2)
        self.labelsda = QtWidgets.QLabel(self.tab4)
        self.labelsda.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelsda.setFont(font)
        self.labelsda.setObjectName("labelsda")
        self.gridLayout_25.addWidget(self.labelsda, 0, 3, 1, 2)
        self.label_141 = QtWidgets.QLabel(self.tab4)
        self.label_141.setObjectName("label_141")
        self.gridLayout_25.addWidget(self.label_141, 3, 3, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.tab4)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.gridLayout_25.addWidget(self.line_12, 0, 2, 4, 1)
        self.hospitalRepresentativeName = QtWidgets.QLineEdit(self.tab4)
        self.hospitalRepresentativeName.setObjectName("hospitalRepresentativeName")
        self.gridLayout_25.addWidget(self.hospitalRepresentativeName, 1, 4, 1, 1)
        self.hospitalRepresentativeDesignation = QtWidgets.QLineEdit(self.tab4)
        self.hospitalRepresentativeDesignation.setObjectName("hospitalRepresentativeDesignation")
        self.gridLayout_25.addWidget(self.hospitalRepresentativeDesignation, 2, 4, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 3, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.tab3Back = QtWidgets.QPushButton(self.tab4)
        self.tab3Back.setObjectName("tab3Back")
        self.horizontalLayout_20.addWidget(self.tab3Back)
        self.tab4Save = QtWidgets.QPushButton(self.tab4)
        self.tab4Save.setObjectName("tab4Save")
        self.horizontalLayout_20.addWidget(self.tab4Save)
        self.gridLayout_26.addLayout(self.horizontalLayout_20, 4, 0, 1, 1)
        self.tabs.addTab(self.tab4, "")
        self.gridLayout_23.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        self.department.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Part2 "))
        self.label_25.setText(_translate("MainWindow", "Name"))
        self.label_28.setText(_translate("MainWindow", "Manufacturer"))
        self.label_61.setText(_translate("MainWindow", "Brand"))
        self.label_68.setText(_translate("MainWindow", "Risk Classification"))
        self.label_66.setText(_translate("MainWindow", "Department"))
        self.label_26.setText(_translate("MainWindow", "Model"))
        self.tab0Next.setText(_translate("MainWindow", "Next"))
        self.label_67.setText(_translate("MainWindow", "Description"))
        self.label_65.setText(_translate("MainWindow", "Serial Number"))
        self.department.setItemText(0, _translate("MainWindow", "Emergency"))
        self.department.setItemText(1, _translate("MainWindow", "Cardiology"))
        self.department.setItemText(2, _translate("MainWindow", "Surgery"))
        self.label_24.setText(_translate("MainWindow", "ITEM DETAILS"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab1), _translate("MainWindow", "Tab 1"))
        self.label_20.setText(_translate("MainWindow", "Purchase Price"))
        self.label_27.setText(_translate("MainWindow", "Warranty Start Date"))
        self.label_22.setText(_translate("MainWindow", "Local Purchase order no"))
        self.label_19.setText(_translate("MainWindow", "Purchase Date"))
        self.label_33.setText(_translate("MainWindow", "Warranty End Date"))
        self.label_21.setText(_translate("MainWindow", "Delivery NO"))
        self.purchaseDate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.warrantyStartDate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.warrantyEndDate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_2.setText(_translate("MainWindow", "Purchase details"))
        self.tab1Back.setText(_translate("MainWindow", "Back"))
        self.tab1Next.setText(_translate("MainWindow", "Next"))
        self.label_16.setText(_translate("MainWindow", "Contact Person"))
        self.label_15.setText(_translate("MainWindow", "Adreess"))
        self.Authorised.setText(_translate("MainWindow", "Authorised Service Agent"))
        self.label_17.setText(_translate("MainWindow", "Contact NO"))
        self.label_5.setText(_translate("MainWindow", "Contact Person"))
        self.label_3.setText(_translate("MainWindow", "Address"))
        self.label_4.setText(_translate("MainWindow", "Contact NO"))
        self.label.setText(_translate("MainWindow", "Supplier"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab2), _translate("MainWindow", "Tab 2"))
        self.label_23.setText(_translate("MainWindow", "PART1"))
        self.label_92.setText(_translate("MainWindow", "  PHYSICAL INSPECTION"))
        self.label_6.setText(_translate("MainWindow", "Batch Size :"))
        self.label_7.setText(_translate("MainWindow", "Sample Size :"))
        self.label_8.setText(_translate("MainWindow", "Defects Count :"))
        self.label_62.setText(_translate("MainWindow", "7. Products are operable or functional"))
        self.label_14.setText(_translate("MainWindow", "6. Perishable items are in good condition and expiration dates have not been exceeded /reasonable duration."))
        self.label_12.setText(_translate("MainWindow", "5. Delivery documentation (packing list, certifications, etc.) is valid and acceptable."))
        self.label_9.setText(_translate("MainWindow", "1. Products conform to the purchase order and other relevant requirments. (for example: correct model number, description, size, type, color, ratings, etc.)"))
        self.label_52.setText(_translate("MainWindow", "NA"))
        self.label_11.setText(_translate("MainWindow", "3. No damage, breakage, tampered packaging, possible contaminate etc."))
        self.label_18.setText(_translate("MainWindow", "PASS"))
        self.label_51.setText(_translate("MainWindow", "FAIL"))
        self.label_13.setText(_translate("MainWindow", "4. Unit of measurement count is correct (e.g. if the unit of measurement on the purchase order is one dozen, there should be 12 in the package)."))
        self.label_10.setText(_translate("MainWindow", "2. Quantity ordered against the quantity shipped or delivered."))
        self.label_91.setText(_translate("MainWindow", "PART2"))
        self.label_93.setText(_translate("MainWindow", "  DEFECT LIST"))
        self.label_94.setText(_translate("MainWindow", "Problem/Defect Statement"))
        self.label_95.setText(_translate("MainWindow", "Remarks"))
        self.label_129.setText(_translate("MainWindow", "Suggestion"))
        self.tab2Back.setText(_translate("MainWindow", "Back"))
        self.tab2Next.setText(_translate("MainWindow", "Next"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab3), _translate("MainWindow", "Step 3"))
        self.label_130.setText(_translate("MainWindow", "PART1"))
        self.label_131.setText(_translate("MainWindow", "  CONCLUSION"))
        self.inspectionDone.setText(_translate("MainWindow", "Inspection Done"))
        self.inspectionNOTDone.setText(_translate("MainWindow", "Inspection NOT Done"))
        self.accepted.setText(_translate("MainWindow", "Accepted"))
        self.notAccepted.setText(_translate("MainWindow", "NOT Accepted"))
        self.acceptedWithReservation.setText(_translate("MainWindow", "Accepted with reservations"))
        self.label_132.setText(_translate("MainWindow", "                              Remark:"))
        self.label_133.setText(_translate("MainWindow", "PART2"))
        self.label_134.setText(_translate("MainWindow", "  VERIFICATION OF ACCEPTANCE CHECK DONE"))
        self.label_139.setText(_translate("MainWindow", "Name:"))
        self.label_140.setText(_translate("MainWindow", "Designation:"))
        self.label_136.setText(_translate("MainWindow", "Name:"))
        self.label_137.setText(_translate("MainWindow", "Designation:"))
        self.label_138.setText(_translate("MainWindow", "Date:"))
        self.supplierDate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.hospitalRepresentativeDate.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_135.setText(_translate("MainWindow", "Supplier:"))
        self.labelsda.setText(_translate("MainWindow", "Hospital Representative:"))
        self.label_141.setText(_translate("MainWindow", "Date:"))
        self.tab3Back.setText(_translate("MainWindow", "Back"))
        self.tab4Save.setText(_translate("MainWindow", "Save"))
        self.tabs.setTabText(self.tabs.indexOf(self.tab4), _translate("MainWindow", "Step 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = installation()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
